<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21295" started-at="2015-06-24T05:02:10Z" finished-at="2015-06-24T05:02:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21295" started-at="2015-06-24T05:02:10Z" finished-at="2015-06-24T05:02:31Z">
      <class name="lession1.TestCalculator">
        <test-method status="PASS" signature="initalAppiumSettings()[pri:0, instance:lession1.TestCalculator@4411d970]" name="initalAppiumSettings" is-config="true" duration-ms="2473" started-at="2015-06-24T13:02:10Z" finished-at="2015-06-24T13:02:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initalAppiumSettings -->
        <test-method status="PASS" signature="Redu()[pri:0, instance:lession1.TestCalculator@4411d970]" name="Redu" duration-ms="4815" started-at="2015-06-24T13:02:12Z" finished-at="2015-06-24T13:02:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Redu -->
        <test-method status="FAIL" signature="addition()[pri:0, instance:lession1.TestCalculator@4411d970]" name="addition" duration-ms="3595" started-at="2015-06-24T13:02:17Z" finished-at="2015-06-24T13:02:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<4.5> but was:<4 point 5>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<4.5> but was:<4 point 5>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at lession1.TestCalculator.addition(TestCalculator.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addition -->
        <test-method status="PASS" signature="plus()[pri:0, instance:lession1.TestCalculator@4411d970]" name="plus" duration-ms="6672" started-at="2015-06-24T13:02:21Z" finished-at="2015-06-24T13:02:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- plus -->
        <test-method status="PASS" signature="take()[pri:0, instance:lession1.TestCalculator@4411d970]" name="take" duration-ms="3209" started-at="2015-06-24T13:02:27Z" finished-at="2015-06-24T13:02:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- take -->
        <test-method status="PASS" signature="realse()[pri:0, instance:lession1.TestCalculator@4411d970]" name="realse" is-config="true" duration-ms="512" started-at="2015-06-24T13:02:31Z" finished-at="2015-06-24T13:02:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- realse -->
      </class> <!-- lession1.TestCalculator -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
